#include "sem.h"

// P producers
// C consumers
// must loop N times
// each yeilds() at the end of each loop
// buffer size of B items
// given a Q of numbers where positive = producer ID, negative = consumer ID
// arrage the ready Q
// start with the fist thread in the Q and run it
// before yielding a consumer
// 	prints "if consumer X is consuming an item then print"
// before yielding a producer

#define N 1
Semaphore empty, full; // change
int buffer[N]; // change
int in = 0, out = 0, item = 0; // change




void producer(int id){
	int local = 1;
	while(local <= N){
        int p = P(&empty);
		if(p == 0){
            printf("Producer %d is waiting\n", id);
        }else{
            buffer[in] = item++;
            in = (in+1)%N;
            
            printf("Producer %d is producing item number %d\n", id, local);
            	
           // yield();
        }
		V(&full);
        local++;
		
	}
	return;	
}


void consumer(int id){
	int local = 1;
	while(local <= N){
		if(P(&full) == 0){
            printf("Consumer %d is waiting\n", id);
        }else{
            
            // int consumed = buffer[out];
            // buffer[out] = 0;
        
            printf("Consumer %d is consuming item generated by Producer %d\n", id, buffer[out]);	
            out = (out+1) % N;
            //yield();
        }
		
		V(&empty);
        local++;
	}
	return;	
}	


int main(){
	
	initQueue(&RunQ);
	InitSem(&full, 0);
	InitSem(&empty, 2);

    int B, P, C, times, id;
    char commas[3];
    scanf("%d%c%d%c%d%c%d", &B, &commas[0], &P, &commas[1], &C, &commas[2], &times);
    int qSize = P+C;
    
    int queue[qSize];
    for(int i = 0; i < qSize; i++){
        
        scanf("%d", &queue[i]);
        if(queue[i] > 0){
            id = queue[i];
            start_thread(producer, id);
            // printf("threadstarted");
        }else{
            id = queue[i] * -1;
            start_thread(consumer, id);
            // printf("threadstarted");
        }
    }

    for(int h = 0; h < qSize; h++){
        //printf("i == %d", h);
        
        
    }
	
	//printf("here\n");
	run();
	return 0;
}